apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: globalappset
  namespace: open-cluster-management-global-set
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: globalappset-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: globalappset-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: remote
        server: "{{server}}"
      project: default
      source:
        path: book-import
        repoURL: https://github.com/cdoan1/application-samples.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: globalappset-placement
  namespace: open-cluster-management-global-set
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
